export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";
export const REGISTER_CONFIRMATION_FAILURE = "REGISTER_CONFIRMATION_FAILURE";
export const REGISTER_CONFIRMATION_SUCCESS = "REGISTER_CONFIRMATION_SUCCESS";