export const REGISTER_SUCCESSFUL = "REGISTER_SUCCESSFUL";
export const REGISTER_UNSUCCESSFUL = "REGISTER_UNSUCCESSFUL";
export const REGISTER_CONFIRMATION_FAILURE = "REGISTER_CONFIRMATION_FAILURE";
export const REGISTER_CONFIRMATION_SUCCESS = "REGISTER_CONFIRMATION_SUCCESS";