export const GET_CLIENT_SERVICE_REQUESTED = 'GET_CLIENT_SERVICE_REQUESTED';
export const GET_CLIENT_SERVICE_SUCCESS = 'GET_CLIENT_SERVICE_SUCCESS';
export const GET_CLIENT_SERVICE_FAILURE = 'GET_CLIENT_SERVICE_FAILURE';

export const ADD_CLIENT_SERVICE_REQUESTED = 'ADD_CLIENT_SERVICE_REQUESTED';
export const ADD_CLIENT_SERVICE_SUCCESS = 'ADD_CLIENT_SERVICE_SUCCESS';
export const ADD_CLIENT_SERVICE_FAILURE = 'ADD_CLIENT_SERVICE_FAILURE';