export const GET_USER_SERVICES_REQUESTED = "USER_APP:SERVICES::GET_USER_SERVICES_REQUESTED";
export const GET_USER_SERVICES_SUCCESS = "USER_APP:SERVICES::GET_USER_SERVICES_SUCCESS";
export const GET_USER_SERVICES_FAILURE = "USER_APP:SERVICES::GET_USER_SERVICES_FAILURE";

export const GET_CLIENT_PROFILE_AND_SERVICES_REQUESTED = "USER_APP:SERVICES::GET_CLIENT_PROFILE_AND_SERVICES_REQUESTED";
export const GET_CLIENT_PROFILE_AND_SERVICES_SUCCESS = "USER_APP:SERVICES::GET_CLIENT_PROFILE_AND_SERVICES_SUCCESS";
export const GET_CLIENT_PROFILE_AND_SERVICES_FAILURE = "USER_APP:SERVICES::GET_CLIENT_PROFILE_AND_SERVICES_FAILURE";

export const SUBSCRIBE_SUCCESS = "USER_APP:SERVICES::SUBSCRIBE_SUCCESS";
export const SUBSCRIBE_FAILURE = "USER_APP:SERVICES::SUBSCRIBE_FAILURE";