export const LOAD_USERSERVICES_REQUESTED = 'LOAD_USERSERVICES_REQUESTED';
export const LOAD_USERSERVICES_SUCCESS = 'LOAD_USERSERVICES_SUCCESS';
export const LOAD_USERSERVICES_FAILURE = 'LOAD_USERSERVICES_FAILURE';