export const LOAD_CLIENT_SERVICES_REQUESTED = "LOAD_CLIENT_SERVICES_REQUESTED";
export const LOAD_CLIENT_SERVICES_SUCCESS = "LOAD_CLIENT_SERVICES_SUCCESS";
export const LOAD_CLIENT_SERVICES_FAILURE = "LOAD_CLIENT_SERVICES_FAILURE";

export const ADD_CLIENT_SERVICE_REQUESTED = "ADD_CLIENT_SERVICE_REQUESTED";
export const ADD_CLIENT_SERVICE_SUCCESS = "ADD_CLIENT_SERVICE_SUCCESS";