export const LOAD_CLIENT_SERVICES_REQUESTED = "LOAD_CLIENT_SERVICES_REQUESTED";
export const LOAD_CLIENT_SERVICES_SUCCESS = "LOAD_CLIENT_SERVICES_SUCCESS";
export const LOAD_CLIENT_SERVICES_FAILURE = "LOAD_CLIENT_SERVICES_FAILURE";